/* eslint-disable import/no-commonjs */
const fs = require('fs');
const path = require('path');
const process = require('process');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const webpack = require('webpack');


const isProd = process.env.NODE_ENV === 'production';

const distDirName = 'dist';

const sharedPlugins = [
  new webpack.DefinePlugin({
    'process.env.PORT': JSON.stringify(process.env.PORT || ''),
    'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'development'),
  }),
  new HtmlWebpackPlugin({
    filename: 'index.html',
    chunks: ['index'],
    template: './index.html',
    inject: true,
  }),
];
const prodPlugins = [
  ...sharedPlugins,
  new ExtractTextPlugin('[name]-[hash:6].bundle.css'),
];
const devPlugins = [
  ...sharedPlugins,
  new webpack.HotModuleReplacementPlugin(),
  new webpack.NamedModulesPlugin(),
];

const prodEntry = { index: ['index.tsx'] };
const devEntry = { ...prodEntry };

const rhlBabelLoader = {
  loader: 'babel-loader',
  options: {
    babelrc: true,
    plugins: ['react-hot-loader/babel'],
  },
};
const urlLoader = 'url-loader?limit=16384&name=[path][name]-[hash:6].[ext]';
const tsLoader = 'ts-loader';
const styleLoader = 'style-loader?sourceMap';
const cssModulesLoader = 'typings-for-css-modules-loader?modules&sass&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]&banner=// This file automatically generated by typings-for-css-modules-loader';
const cssLoader = 'css-loader';
const postCssLoader = {
  loader: 'postcss-loader',
  options: {
    ident: 'postcss',
    plugins: (loader) => [
      require('autoprefixer')(),
    ],
    sourceMap: true,
  },
};
const sassLoader = 'sass-loader?sourceMap';

module.exports = {
  context: path.resolve(__dirname),

  entry: isProd ? prodEntry : devEntry,

  output: {
    publicPath: '/', // Where you uploaded your bundled files. (Relative to server root)
    path: path.resolve(__dirname, distDirName), // Local disk directory to store all your output files (Absolute path)
    filename: '[name]-[hash:6].bundle.js',
  },

  module: {
    rules: [
      {
        test: /\.(j|t)sx?$/,
        exclude: [path.resolve(__dirname, 'node_modules')],
        use: isProd ? [tsLoader] : [rhlBabelLoader, tsLoader],
      },
      {
        test: /\.(png|jpg|gif)$/,
        use: [urlLoader]
      },
      {
        test: /\.(s*)css$/,
        include: [path.resolve(__dirname, 'node_modules'), path.resolve(__dirname, 'styles')],
        use: isProd
          ? ExtractTextPlugin.extract({ use: [cssLoader, postCssLoader, sassLoader], fallback: styleLoader })
          : [styleLoader, cssLoader, postCssLoader, sassLoader],
      },
      {
        test: /\.(s*)css$/,
        include: [path.resolve(__dirname, 'components')],
        use: isProd
          ? ExtractTextPlugin.extract({ use: [cssModulesLoader, postCssLoader, sassLoader], fallback: styleLoader })
          : [styleLoader, cssModulesLoader, postCssLoader, sassLoader],
      },
    ],
  },

  resolve: {
    extensions: ['.ts', '.tsx', '.js', '.jsx', '.json', '*'],
    modules: [
      path.join(__dirname, ''),
      path.join(__dirname, 'node_modules'),
    ],
  },

  devServer: {
    publicPath: '/', // URL path where the webpack files are served from
    contentBase: path.join(__dirname, distDirName), // A directory to serve files non-webpack files from
    host: '0.0.0.0',
    port: process.env.PORT,
    disableHostCheck: true,
    hot: true,
    inline: true,
    watchOptions: {
      aggregateTimeout: 300,
      poll: 1000,
      ignored: /node_modules/,
    },
    historyApiFallback: true,
  },

  plugins: isProd ? prodPlugins : devPlugins,
};
/* eslint-enable import/no-commonjs */
